In [141]:
#нет 54, 63, 66, 68, 73, 75

In [ ]:
import numpy as np #1. Import the numpy package under the name `np`

In [2]:
np.version.version #2 Print the numpy version and the configuration


'1.21.5'

In [3]:
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/dpego/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/dpego/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/dpego/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/dpego/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/dpego/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/dpego/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/dpego/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/dpego/anaconda3\\Library\\include']
Supported SIMD extensions in this NumPy install:
   

In [4]:
print(np.zeros(10)) #3 Create a null vector of size 10

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
x = np.arange(10) #4 How to find the memory size of any array
print(f'{x.size} = число элементов массива',f'{x.itemsize} = сколько один элемент занимает в памяти (в байтах)', sep='\n')
print(f'{x.size * x.itemsize} = объем памяти, занимаемый массивом (в байтах)')

10 = число элементов массива
4 = сколько один элемент занимает в памяти (в байтах)
40 = объем памяти, занимаемый массивом (в байтах)


In [9]:
print(np.info(np.add)) #5 How to get the documentation of the numpy add function from the command line?

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [10]:
#6  Create a null vector of size 10 but the fifth value which is 1
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [11]:
#7. Create a vector with values ranging from 10 to 49 
print(np.arange(10,50))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [13]:
#8 Reverse a vector (first element becomes last)
# первый способ
a = np.arange(10)
a = a[::-1]
#второй способ - с flip
b = np.arange(10)
print(a, np.flip(b))

[9 8 7 6 5 4 3 2 1 0] [9 8 7 6 5 4 3 2 1 0]


In [14]:
#9 Create a 3x3 matrix with values ranging from 0 to 8
print(np.arange(9).reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [19]:
#10. Find indices of non-zero elements from [1,2,0,0,4,0]
a = [1,2,0,0,4,0]
k = 0
nozero =[]
for i in a:
    if i != 0:
        nozero.append(k)
    k += 1
# либо сразу np.nonzero
print(nozero, np.nonzero(a))

[0, 1, 4] (array([0, 1, 4], dtype=int64),)


In [20]:
#11. Create a 3x3 identity matrix - единичная матрица 3х3
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
#12 Create a 3x3x3 array with random values
print(np.random.random((3,3,3)))

[[[0.70529312 0.13708225 0.20168712]
  [0.3900066  0.64139626 0.53790767]
  [0.24620153 0.2522316  0.73843631]]

 [[0.5167881  0.92028791 0.41949969]
  [0.05355467 0.26215467 0.69798304]
  [0.48734891 0.72364643 0.9237195 ]]

 [[0.50081703 0.74156374 0.81789415]
  [0.58389558 0.78405964 0.46536295]
  [0.79284372 0.09380273 0.57695623]]]


In [27]:
#13 Create a 10x10 array with random values and find the minimum and maximum values
a = np.random.random((10,10))
print(a.min(), a.max())

0.0020987374710397244 0.9979852153190276


In [30]:
#14. Create a random vector of size 30 and find the mean value
a = np.random.random(30)
print(a.mean())

0.527055432392459


In [38]:
#15. Create a 2d array with 1 on the border and 0 inside
a = np.ones((3,3))
a[1][1] = 0
b = np.ones((4,4))
b[1:-1,1:-1] = 0        
print(a, b, sep=2*'\n')

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [40]:
#16. How to add a border (filled with 0's) around an existing array?
a = np.ones((7,7))
a[:, [0, -1]], a[[0, -1], :] = 0, 0
print(a)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [42]:
#17. What is the result of the following expression?
"""(0 * np.nan) nan - недопустимое значение, inf - бесконечность, здесь результат = nan
(np.nan == np.nan) False
(np.inf > np.nan) False
(np.nan - np.nan) nan
(np.nan in set([np.nan])) True
(0.3 == 3 * 0.1) False  """

'(0 * np.nan) nan - недопустимое значение, inf - бесконечность, здесь результат = nan\n(np.nan == np.nan) False\n(np.inf > np.nan) False\n(np.nan - np.nan) nan\n(np.nan in set([np.nan])) True\n(0.3 == 3 * 0.1) False  '

In [44]:
#18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
a = np.diag(1 + np.arange(4), k=-1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [48]:
#19. Create a 8x8 matrix and fill it with a checkerboard pattern
a = np.ones((8,8))
for i in range(8):
    for j in range(8):
        if (i + j) % 2 == 0:
            a[i][j] = '0'
        else:
            a[i][j] = '1'
print(a)


[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [51]:
#20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
print(np.unravel_index(99,(6,7,8))) #по сути требуется из плоского представления массива перевести в трехмерное - unravel это и делает,получая индекс 100-го элемента в трехмерии представлении
a = np.arange(6 * 7 * 8)
flag = 11312414 # проверим непосредственно через флаг, задав случайное число (которого точно нет среди чисел массива)
a[99] = flag 
a = a.reshape(6,7,8)
for i in range(6):
    for j in range(7):
        for k in range(8):
            if a[i][j][k] == flag:
                print(i, j, k)

(1, 5, 3)
1 5 3


In [52]:
#21. Create a checkerboard 8x8 matrix using the tile function
print(np.tile( np.array([[0,1],[1,0]]), (4,4)))


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [53]:
#22. Normalize a 5x5 random matrix
# требуется от каждого элемента отнять среднее и поделить на среднеквадратичное отклонение
a = np.random.random((5,5))
a = (a - np.mean (a)) / (np.std (a))
print(a)

[[ 1.09611213 -0.33909996  1.07950369 -1.62303055 -0.28969114]
 [-0.52433827  1.25237953  0.18917008  1.32170361  0.10649142]
 [-1.47966912  1.48748154  1.1553958  -0.19557155 -0.03727666]
 [ 1.09735979 -0.72132504 -1.57011096  1.00807567 -0.9838094 ]
 [-1.30406153  0.70000317  0.45940074 -0.81256652 -1.07252647]]


In [55]:
#23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)
a = np.dtype([("r", np.ubyte, 1), ("g", np.ubyte, 1), ("b", np.ubyte, 1), ("a", np.ubyte, 1)])
print(a)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


C:\Users\dpego\AppData\Local\Temp\ipykernel_10136\3997703392.py:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1), ("g", np.ubyte, 1), ("b", np.ubyte, 1), ("a", np.ubyte, 1)])


In [56]:
#24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
a = np.random.rand(5,3)
b = np.random.rand(3,2)
print("{}\n".format(a))
print("{}\n".format(b))
print("Результат перемножения матриц:")
print(np.dot(a, b))


[[0.06746915 0.13947083 0.96357899]
 [0.81610207 0.86490824 0.43614195]
 [0.08999808 0.03225229 0.41477926]
 [0.90652117 0.07315001 0.2728351 ]
 [0.86519048 0.09773281 0.5578647 ]]

[[0.75858725 0.7187709 ]
 [0.35174882 0.73250539]
 [0.83826875 0.71930583]]

Результат перемножения матриц:
[[0.90797809 0.84376598]
 [1.28891924 1.53385981]
 [0.42731259 0.38666612]
 [0.94211497 0.90141569]
 [1.15834042 1.09473888]]


In [65]:
#25. Given a 1D array, negate all elements which are between 3 and 8, in place.
a = np.arange(11)
for i in range(len(a)):
    if 3 < a[i] < 8:
        a[i] = -a[i]
print(a)


[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


In [66]:
#26 What is the output of the following script?
print(sum(range(5),-1)) # 9
from numpy import *
print(sum(range(5),-1)) # 10

9
10


In [67]:
#27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
'''
Z = 5
Z**Z  3125
2 << Z >> 2  16
Z <- Z  False
1j*Z  5j
Z/1/1  5.0
Z<Z>Z False
Вроде как возможно использовать все
'''

'\nZ = 5\nZ**Z  3125\n2 << Z >> 2  16\nZ <- Z  False\n1j*Z  5j\nZ/1/1  5.0\nZ<Z>Z False\nВроде как возможно использовать все\n'

In [70]:
#28. # What is the result of the following expression?
np.array(0) / np.array(0) # nan 
np.array(0) // np.array(0) # 0 
np.array([np.nan]).astype(int).astype(float) # array([-2.14748365e+09])


C:\Users\dpego\AppData\Local\Temp\ipykernel_10136\422508113.py:2: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0) # nan
C:\Users\dpego\AppData\Local\Temp\ipykernel_10136\422508113.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0) # 0


array([-2.14748365e+09])

In [80]:
#29. How to round away from zero a float array ? 
a = np.random.uniform(-10,+10,10)
b = np.trunc(a + np.copysign(0.5,a))
print(a)
print(b)

[-7.4046413  -8.57127368 -0.6024412   5.6138739  -5.52313109  9.00544671
  2.88621606 -5.54055647  0.37869305  9.16507411]
[-7. -9. -1.  6. -6.  9.  3. -6.  0.  9.]


In [82]:
#30. How to find common values between two arrays?
a = np.random.randint(-5, 5, 10)
b = np.random.randint(-5, 5, 10)
c = np.intersect1d(a, b) # пересечение множеств элементов массивов
print(a)
print(b)
print(c)

[ 4  0 -1 -2 -5  1 -2  1 -1  4]
[-4 -2 -4  2 -1 -1  0  4  1 -2]
[-2 -1  0  1  4]


In [ ]:
#31. How to ignore all numpy warnings (not recommended)?
#np.seterr(all="ignore")

In [ ]:
#32. Is the following expressions true? (★☆☆)
np.sqrt(-1) == np.emath.sqrt(-1) # False

In [83]:
#33. How to get the dates of yesterday, today and tomorrow?
today = np.datetime64("today")
yesterday = today - np.timedelta64(1)
tomorrow = today + np.timedelta64(1)
print("Today: {}".format(today))
print("Yesterday: {}".format(yesterday))
print("Tomorrow: {}".format(tomorrow))

Today: 2022-12-19
Yesterday: 2022-12-18
Tomorrow: 2022-12-20


In [84]:
#34. How to get all the dates corresponding to the month of July 2016?
np.arange("2016-07", "2016-08", dtype="datetime64[D]")

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

In [85]:
#35. How to compute ((A+B)*(-A/2)) in place (without copy)?
A = np.random.uniform(-5, 5, 5)
B = np.random.uniform(-5, 5, 5)
print(A)
print(B)
np.add(A, B, out=B)
np.negative(A, out=A)
np.multiply(A, 0.5, out=A)
np.multiply(A, B, out=A)
print(A)

[ 0.90481857 -4.37724296 -0.47559362 -4.41455414  0.8311368 ]
[-3.75892773 -3.35215599 -4.97148942 -2.37997629 -4.35321344]
[  1.29122549 -16.91672857  -1.29529896 -14.99741122   1.46366375]


In [86]:
#36. Extract the integer part of a random array of positive numbers using 4 different methods
a = np.random.uniform(-15, 15, 10)
print(a)
print(a - a % 1) # только для положительных
print(np.floor(a))
print(np.ceil(a) - 1)
print(a.astype(int).astype(float)) 
print(np.trunc(a))

[ -4.48490825  -4.93130917  -3.43340176   5.56880257  -8.91670722
  -4.22402714  -3.93966007   8.35710065 -14.6558092   -9.13011109]
[ -5.  -5.  -4.   5.  -9.  -5.  -4.   8. -15. -10.]
[ -5.  -5.  -4.   5.  -9.  -5.  -4.   8. -15. -10.]
[ -5.  -5.  -4.   5.  -9.  -5.  -4.   8. -15. -10.]
[ -4.  -4.  -3.   5.  -8.  -4.  -3.   8. -14.  -9.]
[ -4.  -4.  -3.   5.  -8.  -4.  -3.   8. -14.  -9.]


In [87]:
#37. Create a 5x5 matrix with row values ranging from 0 to 4
a = np.zeros((5,5))
a += np.arange(5)
print(a)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [88]:
#38. Consider a generator function that generates 10 integers and use it to build an array
n = 10
a = (n * np.random.rand() for x in range(n))
np.fromiter(a, float)

array([5.43767328, 1.18906571, 1.02922344, 5.38313389, 4.27046452,
       4.96078548, 1.95578932, 6.88550891, 4.06217235, 6.78279801])

In [90]:
#39. Create a vector of size 10 with values ranging from 0 to 1, both excluded
a = np.random.uniform(0, 1, 10) 
a = np.linspace(0, 1, 11, endpoint=False)[1:]
print(a)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [91]:
#40. Create a random vector of size 10 and sort it
a = np.random.randint(-15, 15, 10)
np.sort(a)

array([-15, -12, -10,  -9,  -9,  -4,   8,  11,  12,  12])

In [97]:
#41. How to sum a small array faster than np.sum?
#???
#решено
a = np.random.randint(-10, 10, 5)
a_sum = np.add.reduce(a)
print(a)
print(a_sum)

[ 2  9  5 -1  1]
16


In [96]:
#42. Consider two random array A and B, check if they are equal
a = np.random.randint(0, 2, 4)
b = np.random.randint(0, 2, 4)
res1 = np.allclose(A, B) #считаем, что размерность массивов одинакова
res2 = np.array_equal(A, B) # а тут и размерность проверяем тоже
print(a)
print(b)
print(res1)
print(res2)

[0 0 0 1]
[1 0 1 1]
False
False


In [94]:
#43. Make an array immutable (read-only)
a = np.random.randint(-5, 5, 10)
a.flags.writeable = False
print(a)
# попытки поменять что-то в массиве вызовут ValueError
a[0] = 1
print(a)

[-3  3 -5  0 -3  4 -1 -4 -2  3]


ValueError: assignment destination is read-only

In [ ]:
#44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates
#код из домашки:
def cartesian_to_polar(c):
    """Переводит массив, состоящий из 10 пар координат xy 
    в массив координат r phi.
    
    Parameters
    ----------
    c: Array of int.
    Массив размерами 10х2, каждая строка -- декартовы координаты точки. 
    
    Returns
    -------
    p: Array of int. 
    Аналогичный массив из пар полярных координат. В первом столбике r.
    """
    p = np.zeros(20).reshape(10,2)
    for i in range(10):
        p[i][0], p[i][1] = np.sqrt(c[i][0]**2 + c[i][1]**2), np.arctan2(c[i][1], c[i][0])
    return p

In [100]:
#45 Create random vector of size 10 and replace the maximum value by 0
a = np.random.uniform(-10, 10, 10)
print(a)
print("Максимум: {} с индексом {}".format(max(a), np.argmax(a)))
a[np.argmax(a)] = 0
print(a)

[ 8.02408471 -1.32740498  7.24239106 -9.60324798 -2.8249786   3.84054878
 -4.70817693 -5.56855907  1.78292979  6.9094486 ]
Максимум: 8.024084707665281 с индексом 0
[ 0.         -1.32740498  7.24239106 -9.60324798 -2.8249786   3.84054878
 -4.70817693 -5.56855907  1.78292979  6.9094486 ]


In [101]:
#46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1]
a = np.zeros((5,5), [("x", float), ("y", float)])
a["x"], a["y"] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))
print(a)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [102]:
#47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))
a = np.random.uniform(-5, 5, 5)
b = np.random.uniform(-5, 5, 5)
c = 1.0 / np.subtract.outer(a, b)
print(c)

[[-0.29087986 -0.22533232 -1.46463297 -0.53640957 -0.20847826]
 [-0.57151669 -0.36366618  0.99467808 -5.6775662  -0.3216936 ]
 [ 0.87683355  7.12134425  0.2567033   0.36845092 -4.57979285]
 [-0.32701555 -0.24642663 -3.30165935 -0.67369092 -0.22640947]
 [ 0.17847036  0.21724363  0.11964224  0.13933846  0.23560714]]


In [104]:
#48. Print the minimum and maximum representable value for each numpy scalar type
for dtype in [np.uint8, np.int8, np.uint16, np.int16, np.uint32, np.int32, np.uint64, np.int64]:
    print(dtype)
    print("Min: {}".format(np.iinfo(dtype).min))
    print("Max: {}".format(np.iinfo(dtype).max))
    print()
for dtype in [np.float16, np.float32, np.float64]:
    print(dtype)
    print("Min: {}".format(np.finfo(dtype).min))
    print("Max: {}".format(np.finfo(dtype).max))
    print("Eps: {}".format(np.finfo(dtype).eps))
    print()

<class 'numpy.uint8'>
Min: 0
Max: 255

<class 'numpy.int8'>
Min: -128
Max: 127

<class 'numpy.uint16'>
Min: 0
Max: 65535

<class 'numpy.int16'>
Min: -32768
Max: 32767

<class 'numpy.uint32'>
Min: 0
Max: 4294967295

<class 'numpy.int32'>
Min: -2147483648
Max: 2147483647

<class 'numpy.uint64'>
Min: 0
Max: 18446744073709551615

<class 'numpy.int64'>
Min: -9223372036854775808
Max: 9223372036854775807

<class 'numpy.float16'>
Min: -65504.0
Max: 65504.0
Eps: 0.0009765625

<class 'numpy.float32'>
Min: -3.4028234663852886e+38
Max: 3.4028234663852886e+38
Eps: 1.1920928955078125e-07

<class 'numpy.float64'>
Min: -1.7976931348623157e+308
Max: 1.7976931348623157e+308
Eps: 2.220446049250313e-16



In [110]:
#49. How to print all the values of an array?
'''np.set_printoptions(threshold=np.nan)
a = np.arange(50)
print(a) '''
#тут беда
np.set_printoptions(threshold=float("inf"))
a = np.arange(50)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [111]:
#50. How to find the closest value (to a given scalar) in a vector?
a = np.arange(100)
scalar = np.random.uniform(0, 100)
print(a)
print(scalar)
print(a[(np.abs(a - scalar)).argmin()])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
33.87944123574292
34


In [115]:
#51. Create a structured array representing a position (x,y) and a color (r,g,b)
dtype = [ ("позиция", [("x", float, 1), ("y", float, 1)]),
            ("цвет", [("r", float, 1), ("g", float, 1),("b", float, 1)])
        ]
print(np.zeros(1, dtype))


[((0., 0.), (0., 0., 0.))]


C:\Users\dpego\AppData\Local\Temp\ipykernel_10136\1589470848.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  print(np.zeros(1, dtype))


In [118]:
#52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances
a = np.random.randint(-5, 5, (100,2))
x,y = np.atleast_2d(a[:,0], a[:,1])
distance = np.sqrt((x - x.T) ** 2 + (y - y.T) ** 2) # T - транспонирование


In [119]:
#53. How to convert a float (32 bits) array into an integer (32 bits) in place?
a = np.random.uniform(-10, 10, 10)
print(a)
print(a.astype(int, copy=False))

[ 5.07078692 -5.87670675 -7.71470786  2.17697685  0.2501549   3.21132647
 -7.9183108  -9.54258868 -9.81924026 -2.06782895]
[ 5 -5 -7  2  0  3 -7 -9 -9 -2]


In [ ]:
#54. How to read the following file?
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```
#что надо сделать??

In [120]:
#55. What is the equivalent of enumerate for numpy arrays?
a = np.random.randint(-10, 10, 9).reshape(3,3)
print(a)
print("\используем np.ndenumerate:")
for i,v in np.ndenumerate(a):
    print(i, v)
print("\используем np.ndindex:")
for i in np.ndindex(a.shape):
    print(i, a[i])

[[ -3 -10  -8]
 [  7  -1  -6]
 [  9  -6   0]]
\используем np.ndenumerate:
(0, 0) -3
(0, 1) -10
(0, 2) -8
(1, 0) 7
(1, 1) -1
(1, 2) -6
(2, 0) 9
(2, 1) -6
(2, 2) 0
\используем np.ndindex:
(0, 0) -3
(0, 1) -10
(0, 2) -8
(1, 0) 7
(1, 1) -1
(1, 2) -6
(2, 0) 9
(2, 1) -6
(2, 2) 0


In [121]:
#56. Generate a generic 2D Gaussian-like array
x,y = np.meshgrid(np.linspace(-1, 1, 10), np.linspace(-1, 1, 10))
R = np.sqrt(x ** 2 + y ** 2)
sigma = 1.0
mu = 0.0
gauss = np.exp(-((R - mu) ** 2 / (2.0 * sigma ** 2)))
print(gauss)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [123]:
#57. How to randomly place p elements in a 2D array?
b, c = 10, 3
a = np.zeros((b,b))
np.put(a, np.random.choice(range(b ** 2), c, replace=False), 1)
print(a)

[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [126]:
#58. Subtract the mean of each row of a matrix
a = np.random.randint(-10, 10, (5,10))
a_ = a - a.mean(axis=1, keepdims=True)
print("Создаем случайный массив: \n{}".format(a))
print("\nСреднее каждой строки массива:")
for row in a:
    print(row.mean())
print("\nНовый массив со средним значением каждой строки, вычтенным из каждого элемента: \n{}".format(a_))

Создаем случайный массив: 
[[ -4  -3  -2  -1  -6   2   8  -5  -6  -2]
 [ -5   2  -8  -1  -8   0  -4  -9  -4   2]
 [  6  -3   0  -8 -10   0   5   5  -5  -9]
 [ -1  -9   7   6   2  -2  -7   1  -3 -10]
 [ -9   3  -6  -7   9   4   0  -1 -10   1]]

Среднее каждой строки массива:
-1.9
-3.5
-1.9
-1.6
-1.6

Новый массив со средним значением каждой строки, вычтенным из каждого элемента: 
[[-2.1 -1.1 -0.1  0.9 -4.1  3.9  9.9 -3.1 -4.1 -0.1]
 [-1.5  5.5 -4.5  2.5 -4.5  3.5 -0.5 -5.5 -0.5  5.5]
 [ 7.9 -1.1  1.9 -6.1 -8.1  1.9  6.9  6.9 -3.1 -7.1]
 [ 0.6 -7.4  8.6  7.6  3.6 -0.4 -5.4  2.6 -1.4 -8.4]
 [-7.4  4.6 -4.4 -5.4 10.6  5.6  1.6  0.6 -8.4  2.6]]


In [127]:
#59. How to sort an array by the nth column?
arr = np.random.randint(-10, 10, (3,3))
print("Создаем случайный массив: \n{}\n".format(arr))
print("Сортируем по n-ому столбцу \n{}".format(arr[arr[:,1].argsort()]))

Создаем случайный массив: 
[[  5  -3  -3]
 [  4 -10  -9]
 [  2  -5  -2]]

Сортируем по n-ому столбцу 
[[  4 -10  -9]
 [  2  -5  -2]
 [  5  -3  -3]]


In [129]:
#60 How to tell if a given 2D array has null columns (columns with all 0s)?
a = np.random.randint(0, 3, (3,10))
print(a)
print((~a.any(axis=0)).any())

[[2 1 2 1 1 1 0 0 2 1]
 [0 1 1 0 0 0 2 0 1 1]
 [0 1 2 0 1 2 2 0 2 0]]
True


In [130]:
#61. Find the nearest value from a given value in an array
a = np.random.rand(10)
val = 0.5
nearest = a.flat[np.abs(a - val).argmin()]
print(a)
print(nearest)

[0.8636334  0.62495974 0.21455323 0.83452789 0.82812465 0.23244946
 0.12253752 0.5423145  0.16357766 0.0818279 ]
0.5423145038970345


In [131]:
#62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?
a1 = np.arange(3).reshape(1,3)
a2 = np.arange(3).reshape(3,1)
iterator = np.nditer([a1, a2, None])
for x,y,z in iterator:
    z[...] = x + y
print(a1)
print(a2)
print(iterator.operands[2])

[[0 1 2]]
[[0]
 [1]
 [2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [132]:
#64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?
a = np.ones(10)
I = np.random.randint(0,len(a),20)
a += np.bincount(I, minlength=len(a))
print(a)

[2. 2. 3. 4. 4. 2. 4. 4. 2. 3.]


In [133]:
#65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)?
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [134]:
#67. Considering a four dimensions array, how to get sum over the last two axis at once?
a = np.random.randint(0,10,(3,4,3,4))
sum = a.sum(axis=(-2,-1))
print(sum)

[[48 49 49 62]
 [51 54 64 36]
 [52 54 52 57]]


In [136]:
#69. How to get the diagonal of a dot product?
a1 = np.random.uniform(0,1,(5,5))
a2 = np.random.uniform(0,1,(5,5))

print(np.diag(np.dot(a1, a2)))

[0.94740225 0.62489817 0.62140148 1.98517579 1.22188787]


In [137]:
#70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?
a = np.array([1,2,3,4,5])
z = 3
a0 = np.zeros(len(a) + (len(a) - 1) * (z))
a0[::z + 1] = a
print(a0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [138]:
#71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?
a1 = np.ones((5,5,3))
a2 = np.ones((5,5))
print(a1 * a2[:,:,None])

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [140]:
#72. How to swap two rows of an array?
a = np.random.randint(1,20, (3,4))
print('Заданный массив: \n\n', a)
a[[0,2]] = a[[2,0]]
print('А теперь поменяли строки местами: \n\n ', a)

Заданный массив: 

 [[ 3 11  6  5]
 [10 10  9 12]
 [18 15  7  5]]
А теперь поменяли строки местами: 

  [[18 15  7  5]
 [10 10  9 12]
 [ 3 11  6  5]]


In [142]:
#73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles
#??

In [143]:
#74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? 
sample_array = np.random.randint(1,10, 10)    # Creating any random 1D array.
C = np.sort(sample_array)
print('Массив С: \t\t', C)
bin_count = np.bincount(C)

print('\n\n Количество битов массива С: \t\t',bin_count)

print(f'\n\n Размер С {len(C)} и количество битов {len(bin_count)}')
## Now we create A ###

if len(C) == len(bin_count):
    A = np.repeat(np.arange(len(bin_count)), bin_count)  
    print('\n\nМассив В: \t\t', A)
else:
    print('\n\n Ошиблись с размером, заново..')

Массив С: 		 [1 1 1 3 3 4 5 6 8 9]


 Количество битов массива С: 		 [0 3 0 2 1 1 1 0 1 1]


 Размер С 10 и количество битов 10


Массив В: 		 [1 1 1 3 3 4 5 6 8 9]


In [151]:
#76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) 
def rolling(a,window):
    a_index = np.repeat(np.arange(3).reshape(-1,3),len(a)-window +1,axis = 0) + np.arange(len(a)-window +1)[:,np.newaxis]
    return a[a_index]

a = rolling(np.arange(10),3)
print(a)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [156]:
#77. How to negate a boolean, or to change the sign of a float inplace?
a = np.random.randint(0,2,5)
print(a,np.logical_not(a)) # логическое not - 0 из начального массива стали 1
#руками можно применить оператор not к каждому элементу массива - это если без numpy
a = np.random.uniform(-1.0,1.0,5)
print(a,np.negative(a)) #поменяли знак

[1 1 0 0 0] [False False  True  True  True]
False
[ 0.30120844 -0.13099002 -0.04228541 -0.53324946 -0.74983142] [-0.30120844  0.13099002  0.04228541  0.53324946  0.74983142]


In [161]:
#78 Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])?
def find_dist(P0, P1, p):
  R = P0 - P1 #разница между набором точек
  L = (R ** 2).sum(axis = 1)
  U = (P1[:,0] - P0[:,0]) * p[:,1] - (P1[:,1] - P0[:,1]) * p[:,0] + P0[:,0] * P1[:,1] - P0[:,1] * P1[:,0]
  D = np.sqrt(U ** 2 / L)
  return D
P0 = np.random.uniform(-1e5,1e5,(10,2))
P1 = np.random.uniform(-1e5,1e5,(10,2))
p  = np.random.uniform(-1e5,1e5,( 1,2))
print(find_dist(P0, P1, p))

[131227.00776318  64967.61212194   5915.04497321  55890.16638512
  98641.42599584  18768.6549865   22319.32703786  73786.63681698
 149645.44232627 118778.55588279]


In [162]:
#79 Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])?
#Используем функцию из предыдущей задачи

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [166]:
#82. Compute a matrix rank
a = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(a)
rang = np.sum(S > 1e-10)
print(rang)

10
